// ── Furniture Assets ─────────────────────────────────────────
export const FURNITURE_ASSETS: Record<string, string> = {
  // 桌子
  desk: 'desk_beige',
  desk_r: 'desk_beige_r',
  desk_gray: 'desk_gray',
  desk_gray_l: 'desk_gray_l',
  desk_gray_single: 'desk_gray_single',
  desk_gray_wide: 'desk_gray_wide',
  desk_long_l: 'desk_long_l',
  desk_long_m: 'desk_long_m',
  desk_long_r: 'desk_long_r',
  desk_long_l2: 'desk_long_l2',
  standing_desk: 'standing_desk',
  standing_desk2: 'standing_desk2',
  desk_beige_tl: 'desk_beige_tl',
  desk_beige_tm: 'desk_beige_tm',
  desk_beige_tr: 'desk_beige_tr',
  // 隔間桌面
  cubicle_tl: 'cubicle_tl',
  cubicle_tm: 'cubicle_tm',
  cubicle_tr: 'cubicle_tr',
  cubicle_ml: 'cubicle_ml',
  cubicle_mm: 'cubicle_mm',
  cubicle_mr: 'cubicle_mr',
  cubicle_bl: 'cubicle_bl',
  cubicle_bm: 'cubicle_bm',
  cubicle_br: 'cubicle_br',
  // 椅子
  chair: 'chair_front',
  chair_back: 'chair_back',
  chair_side: 'chair_side_r',
  chair_side_l: 'chair_side_l',
  chair_exec: 'chair_exec',
  chair_exec_back: 'chair_exec_back',
  // 植物
  plant: 'plant_pot',
  plant_big: 'plant_big',
  plant_bush: 'plant_bush',
  plant_tall: 'plant_tall',
  // 書架/櫃
  bookshelf: 'bookshelf',
  bookshelf2: 'bookshelf2',
  cabinet: 'cabinet',
  shelf: 'shelf_items',
  wardrobe: 'wardrobe',
  // 沙發
  sofa: 'sofa_single',
  sofa_top: 'sofa_top',
  sofa_mid: 'sofa_mid',
  sofa_bottom: 'sofa_bottom',
  sofa_wide: 'sofa_wide',
  sofa_narrow: 'sofa_narrow',
  sofa_l_tl: 'sofa_l_tl',
  sofa_l_tr: 'sofa_l_tr',
  sofa_l_corner: 'sofa_l_corner',
  sofa_l_bl: 'sofa_l_bl',
  sofa_l_front: 'sofa_l_front',
  armchair_blue: 'armchair_blue',
  armchair_gray: 'armchair_gray',
  armchair_light: 'armchair_light',
  armchair_brown: 'armchair_brown',
  // 設備
  printer: 'printer',
  printer_side: 'printer_side',
  printer_front: 'printer_front',
  copier: 'copier',
  fax: 'fax',
  shredder: 'shredder',
  vending: 'vending',
  vending2: 'vending2',
  vending3: 'vending3',
  vending4: 'vending4',
  copier_large: 'copier_large',
  copier_large2: 'copier_large2',
  server: 'server',
  pos_terminal: 'pos_terminal',
  washer: 'washer',
  // 冷氣/空調
  ac_unit: 'ac_unit',
  ac_unit_r: 'ac_unit_r',
  ac_outdoor: 'ac_outdoor',
  ac_outdoor2: 'ac_outdoor2',
  // 飲水/咖啡
  water_dispenser: 'water_dispenser',
  water_dispenser2: 'water_dispenser2',
  water_cooler: 'water_cooler',
  water_jug: 'water_jug',
  water_jug2: 'water_jug2',
  water_station: 'water_station',
  coffee_table: 'coffee_table',
  coffee_station: 'coffee_station',
  // 隔板/白板/看板
  divider_tl: 'divider_tl',
  divider_tm: 'divider_tm',
  divider_tr: 'divider_tr',
  divider_ml: 'divider_ml',
  divider_mm: 'divider_mm',
  divider_mr: 'divider_mr',
  divider_pole: 'divider_pole',
  board: 'board_wide',
  board_top: 'board_top',
  board_cork: 'board_cork',
  whiteboard: 'whiteboard_small',
  screen_tv: 'screen_tv',
  screen_wide: 'screen_wide',
  screen_chart: 'screen_chart',
  screen_dashboard: 'screen_dashboard',
  // 壁掛裝飾
  painting_abstract: 'painting_abstract',
  painting_warm: 'painting_warm',
  painting_colorful: 'painting_colorful',
  painting_portrait: 'painting_portrait',
  certificate_a: 'certificate_a',
  certificate_b: 'certificate_b',
  certificate_c: 'certificate_c',
  diploma: 'diploma',
  chart_bar: 'chart_bar',
  chart_pie: 'chart_pie',
  // 桌上小物
  monitor: 'monitor',
  monitor_on: 'monitor_large',
  monitor_angled: 'monitor_angled',
  laptop: 'laptop',
  laptop_side: 'laptop_side',
  keyboard: 'keyboard',
  keyboard_mouse: 'keyboard_mouse',
  mouse_pad: 'mouse_pad',
  mouse_white: 'mouse_white',
  mouse_gray: 'mouse_gray',
  desk_lamp: 'desk_lamp',
  phone: 'phone',
  mug: 'mug',
  briefcase: 'briefcase',
  folder_orange: 'folder_orange',
  folder_blue: 'folder_blue',
  globe: 'globe',
  key: 'key',
  // 雜物/背包
  backpack_blue: 'backpack_blue',
  backpack_green: 'backpack_green',
  backpack_brown: 'backpack_brown',
  cash_pile: 'cash_pile',
}

// ── Furniture Catalog (for editor palette) ───────────────────
export interface CatalogCategory {
  name: string
  items: string[] // keys in FURNITURE_ASSETS
}

export const FURNITURE_CATALOG: CatalogCategory[] = [
  {
    name: '桌子',
    items: ['desk', 'desk_r', 'desk_gray', 'desk_gray_l', 'desk_gray_single', 'desk_gray_wide',
            'desk_long_l', 'desk_long_m', 'desk_long_r', 'desk_long_l2',
            'desk_beige_tl', 'desk_beige_tm', 'desk_beige_tr',
            'standing_desk', 'standing_desk2'],
  },
  {
    name: '椅子',
    items: ['chair', 'chair_back', 'chair_side', 'chair_side_l', 'chair_exec', 'chair_exec_back'],
  },
  {
    name: '植物',
    items: ['plant', 'plant_big', 'plant_bush', 'plant_tall'],
  },
  {
    name: '書架/櫃',
    items: ['bookshelf', 'bookshelf2', 'cabinet', 'shelf', 'wardrobe'],
  },
  {
    name: '沙發/椅',
    items: ['sofa', 'sofa_top', 'sofa_mid', 'sofa_bottom',
            'sofa_wide', 'sofa_narrow',
            'sofa_l_tl', 'sofa_l_tr', 'sofa_l_corner', 'sofa_l_bl', 'sofa_l_front',
            'armchair_blue', 'armchair_gray', 'armchair_light', 'armchair_brown'],
  },
  {
    name: '設備',
    items: ['printer', 'printer_side', 'printer_front', 'copier', 'copier_large', 'copier_large2',
            'fax', 'shredder', 'vending', 'vending2', 'vending3', 'vending4',
            'server', 'pos_terminal', 'washer'],
  },
  {
    name: '冷氣/空調',
    items: ['ac_unit', 'ac_unit_r', 'ac_outdoor', 'ac_outdoor2'],
  },
  {
    name: '飲水/咖啡',
    items: ['water_dispenser', 'water_dispenser2', 'water_cooler',
            'water_jug', 'water_jug2', 'water_station',
            'coffee_table', 'coffee_station'],
  },
  {
    name: '隔板/白板',
    items: ['divider_tl', 'divider_tm', 'divider_tr', 'divider_ml', 'divider_mm', 'divider_mr',
            'divider_pole', 'board', 'board_top', 'board_cork', 'whiteboard'],
  },
  {
    name: '螢幕/看板',
    items: ['screen_tv', 'screen_wide', 'screen_chart', 'screen_dashboard'],
  },
  {
    name: '隔間桌面',
    items: ['cubicle_tl', 'cubicle_tm', 'cubicle_tr',
            'cubicle_ml', 'cubicle_mm', 'cubicle_mr',
            'cubicle_bl', 'cubicle_bm', 'cubicle_br'],
  },
  {
    name: '壁掛裝飾',
    items: ['painting_abstract', 'painting_warm', 'painting_colorful', 'painting_portrait',
            'certificate_a', 'certificate_b', 'certificate_c', 'diploma',
            'chart_bar', 'chart_pie'],
  },
]

export const PROPS_CATALOG: CatalogCategory[] = [
  {
    name: '電腦/螢幕',
    items: ['monitor', 'monitor_on', 'monitor_angled', 'laptop', 'laptop_side'],
  },
  {
    name: '鍵盤/滑鼠',
    items: ['keyboard', 'keyboard_mouse', 'mouse_pad', 'mouse_white', 'mouse_gray'],
  },
  {
    name: '辦公小物',
    items: ['phone', 'mug', 'briefcase', 'desk_lamp',
            'folder_orange', 'folder_blue', 'globe', 'key'],
  },
  {
    name: '背包/雜物',
    items: ['backpack_blue', 'backpack_green', 'backpack_brown', 'cash_pile'],
  },
]
